### ISSUE TITLE
Bug - Touching an interactive object gets you stuck.

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#38]
On the Development Branch, touching the doors to a building (Cog or Toon), touching the Trolley, etc. will get you stuck, thus breaking the game.

[toontown-220802_235759.log](https://github.com/PLAYERZER0STUDIOS/Toontown-Fantasy/files/9247856/toontown-220802_235759.log)
.

**Comment by DarthMDev** [comment]
by any chance does uberdog die ?

**Comment by DarthMDev** [comment]
cant replicate this 
doors seem to work maybe it was similar to the issue with loading areas 
possibly fixed by #51

**Comment by GracieLovelight** [comment]
This has been fixed.
