### ISSUE TITLE
(Development) Client refuses to load areas

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#49]
Upon creating a new Toon OR loading into a Toon, the client refuses to load areas. Here is the log file: [toontown-231114_233722.log](https://github.com/PLAYER-ZER0-STUDIO/Toontown-Fantasy/files/13360126/toontown-231114_233722.log)

**Comment by DarthMDev** [comment]
do you have the log from uberdog, ai or astron (anything useful there?) it looks like it just loses connection

**Comment by GracieLovelight** [comment]
I do not appear to have the logs anymore. I will try to get on again to test. However, there's probably a ton more changes that have been made since that I haven't accounted for. I will send those logs when I get them

**Comment by GracieLovelight** [comment]
These are the only two logs given: 

[toontown-240227_193633.log](https://github.com/Arbitrium-Studios/Open-Fantasy/files/14427151/toontown-240227_193633.log)
[events-240227_193627.log](https://github.com/Arbitrium-Studios/Open-Fantasy/files/14427153/events-240227_193627.log)

Everything else appears good but I think Disney might've removed their CDN containing the news or it is incorrect. Regardless, I think we should replace the gamenews with one on the AS CDN or add them locally to the gamefiles and get them from there.

**Comment by DarthMDev** [comment]
ill do some debugging myself when i get a chance

**Comment by GracieLovelight** [comment]
Sounds good. I don't believe it is the only issue but I'll help out whenever and wherever I can!

**Comment by GracieLovelight** [comment]
This should be fixed now! #RIPAcornAcresButteryflies
