### ISSUE TITLE
(Dev Widescreen Fix) Some GUI does not respect widescreen

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#83]
The following GUI does not respect widescreen:

- [ ] The News Button
- [ ] The Cog Gallery Frame

![toontown-screenshot-Sun-Mar-03-02-18-45-2024-8137](https://github.com/Arbitrium-Studios/Open-Fantasy/assets/68795576/4381b100-bf06-442a-b0ea-b6e16f7c5c09)
![toontown-screenshot-Sun-Mar-03-02-22-38-2024-79036](https://github.com/Arbitrium-Studios/Open-Fantasy/assets/68795576/cf639cb3-7f38-415d-a859-2afcdf7e1037)

**Comment by DarthMDev** [comment]
this should be fixed when adding my eventual widescreen update will ignore for now

**Comment by GracieLovelight** [comment]
Alright!
